# Generated by Django 5.2 on 2025-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(max_length=5),
        ),
    ]
